name: light_compressor_v2
description: A powerful and easy-to-use video compression plugin for Flutter.
version: 1.4.0
repository: https://github.com/Farid023/light_compressor_v2
issue_tracker: https://github.com/Farid023/light_compressor_v2/issues

topics:
  - video
  - compression
  - video-compression
  - media
  - compressor

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gurfdev.light_compressor_v2
        pluginClass: LightCompressorPlugin
      ios:
        pluginClass: SwiftLightCompressorPlugin
      macos:
        pluginClass: LightCompressorPlugin
